apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  selector:
    app: bci-microservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
