apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bci-microservice
  template:
    metadata:
      labels:
        app: bci-microservice
    spec:
      containers:
        - name: bci-microservice
          image: bci-microservice:latest
          ports:
            - containerPort: 8080
