server:
  port: 8081 # especifica el número de puerto en el que la aplicación se ejecutará.
spring:
  application:
    name: springboot-bci-microservice #  establece el nombre de la aplicación.
  datasource: #  configura las propiedades para la conexión de la base de datos H2, incluyendo el controlador de la base de datos, la URL, el nombre de usuario y la contraseña encriptados utilizando Jasypt.
#    driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: org.h2.Driver
    password: ENC(+HLaW95AR6oZnEjrC8o4rs1ExUiCjEAx)
    url: 'jdbc:h2:mem:testdb'
#    url: 'jdbc:mysql://172.17.0.2:3306/develop?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true'
    username: ENC(g8Qj4Uy+VXWsthoaM6Tp8g==)
    hikari:
      auto-commit: true
      connectionTimeout: 600000
      maximumPoolSize: 5
      minimumIdle: 2
  h2: # habilita la consola de la base de datos H2
    console:
      enabled: true
      path: /h2-console
  jpa: #  configura las propiedades para la conexión JPA, incluyendo la plataforma de la base de datos y la configuración de Hibernate
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  mvc: #  configura la conversión y el formateo de objetos JSON en la aplicación
    converters:
      preferred-json-mapper: jackson
    format:
      date: "MMM dd, yyyy hh:mm:ss a"

myapp: # configura las propiedades de la aplicación, incluyendo el formato de fecha y el tiempo de expiración del token
  formatDate: "MMM dd, yyyy hh:mm:ss a"
  expirationTokenMs: 300000