server:
  port: 8081
  servlet:
    context-path: /bci-microservice/api
spring:
  profiles:
    active: dev
  application:
    name: springboot-bci-microservice
  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: org.h2.Driver
    password: ENC(NBX2RHYV6K3Gf1eHI93Xad1FwdN0ED9u)
    url: 'jdbc:h2:mem:testdb'
#    url: 'jdbc:mysql://172.17.0.2:3306/develop?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true'
    username: ENC(LTuzsowYJ7DHzacC0mkGNg==)
    hikari:
      auto-commit: true
      connectionTimeout: 600000
      maximumPoolSize: 5
      minimumIdle: 2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    converters:
      preferred-json-mapper: jackson
    format:
      date: "MMM dd, yyyy hh:mm:ss a"

token-properties:
  formatDate: "MMM dd, yyyy hh:mm:ss a"
  expirationTokenMs: 300000